class EasyQuestions {
    companion object {
        val questionsEasy = listOf(
            Question("Welche Programmiersprache ist sehr beliebt für die Entwicklung von Android-Apps?",
                listOf("A) Java", "B) Swift", "C) C++", "D) Kotlin"),
                'D'),
            Question("Welches ist das größte Bundesland in Deutschland?",
                listOf("A) Bayern", "B) Nordrhein-Westfalen", "C) Baden-Württemberg", "D) Niedersachsen"),
                'B'),
            Question("Wer ist der Schöpfer von Facebook?",
                listOf("A) Mark Zuckerberg", "B) Steve Jobs", "C) Bill Gates", "D) Larry Page"),
                'A'),
            Question("Wer ist der Regisseur von Titanic?",
                listOf("A) James Cameron", "B) Steven Spielberg", "C) Martin Scorsese", "D) Quentin Tarantino"),
                'A'),
            Question("Welches ist das größte Land der Welt?",
                listOf("A) USA", "B) China", "C) Russland", "D) Kanada"),
                'C'),
            Question("Welche Stadt ist die Hauptstadt von Deutschland?",
                listOf("A) Berlin", "B) Frankfurt", "C) Hamburg", "D) München"),
                'A'),
            Question("Welches ist das bevölkerungsreichste Land der Welt?",
                listOf("A) China", "B) Indien", "C) USA", "D) Indonesien"),
                'A'),
            Question("Welcher Film gewann den Besten Film bei den Oscars 2021?",
                listOf("A) The Trial of the Chicago 7", "B) Minari", "C) Nomadland", "D) Promising Young Woman"),
                'C'),
            Question("Wer ist der aktuelle Präsident der Vereinigten Staaten?",
                listOf("A) Joe Biden", "B) Donald Trump", "C) Barack Obama", "D) George W. Bush"),
                'A'),
            Question("Welches ist das bevölkerungsreichste Bundesland in Deutschland?",
                listOf("A) Bayern", "B) Nordrhein-Westfalen", "C) Baden-Württemberg", "D) Niedersachsen"),
                'B'),
            Question("Welches ist das größte Meer der Welt?",
                listOf("A) Pazifischer Ozean", "B) Atlantischer Ozean", "C) Indischer Ozean", "D) Arktischer Ozean"),
                'A'),
            Question("Welches ist das höchste Gebäude der Welt?",
                listOf("A) Taipei 101", "B) Burj Khalifa", "C) International Commerce Centre", "D) Shanghai Tower"),
                'B'),
            Question("Wer ist der bekannteste Actionfilmstar der Welt?",
                listOf("A) Arnold Schwarzenegger", "B) Sylvester Stallone", "C) Jackie Chan", "D) Bruce Willis"),
                'C'),
            Question("Welches ist das beliebteste soziale Netzwerk?",
                listOf("A) Twitter", "B) Facebook", "C) Snapchat", "D) Instagram"),
                'D'),
            Question("Wer ist der Komponist von Beethovens 5. Sinfonie?",
                listOf("A) Ludwig van Beethoven", "B) Franz Joseph Haydn", "C) Wolfgang Amadeus Mozart", "D) Johann Sebastian Bach"),
                'A'),
            Question("Welches ist das größte Land in Europa?",
                listOf("A) Deutschland", "B) Russland", "C) Spanien", "D) Frankreich"),
                'B'),
            Question("Welche Stadt ist die Hauptstadt von Frankreich?",
                listOf("A) Marseille", "B) Paris", "C) Toulouse", "D) Lyon"),
                'B'),
            Question("Welches ist das bevölkerungsreichste Land in Europa?",
                listOf("A) Deutschland", "B) Großbritannien", "C) Frankreich", "D) Russland"),
                'A'),
            Question("Welches ist das größte Land in Asien?",
                listOf("A) Türkei", "B) China", "C) Indien", "D) Russland"),
                'B'),
            Question("Welcher Regisseur drehte den Film Inception?",
                listOf("A) Steven Spielberg", "B) Christopher Nolan", "C) Martin Scorsese", "D) Quentin Tarantino"),
                'B'),
            Question("Welcher Künstler malte das Gemälde Mona Lisa?",
                listOf("A) Raphael", "B) Caravaggio", "C) Michelangelo", "D) Leonardo da Vinci"),
                'D'),
            Question("Wer ist der Regisseur von Forrest Gump?",
                listOf("A) Steven Spielberg", "B) Martin Scorsese", "C) Robert Zemeckis", "D) Quentin Tarantino"),
                'C'),
            Question("Welcher US-amerikanischer Schauspieler spielte die Hauptrolle in Titanic?",
                listOf("A) George Clooney", "B) Brad Pitt", "C) Leonardo DiCaprio", "D) Tom Cruise"),
                'C'),
            Question("Welches Land beherbergt die größte Pyramide der Welt?",
                listOf("A) Ägypten", "B) China", "C) Mexiko", "D) Sudan"),
                'A'),
            Question("Welcher US-amerikanischer Präsident war vor Barack Obama im Amt?",
                listOf("A) George W. Bush", "B) Bill Clinton", "C) George H. W. Bush", "D) Ronald Reagan"),
                'A')
        )
    }
}
