class HardQuestions {
    companion object {
        val questionsHard = listOf(
            Question("Welcher Philosoph vertrat den Standpunkt des Determinismus?",
                listOf("A) John Locke", "B) René Descartes", "C) Baruch Spinoza", "D) Immanuel Kant"),
                'C'),
            Question("Welche Theorie besagt, dass die Entwicklung der Gesellschaft durch Klassenkampf bestimmt wird?",
                listOf("A) Feminismus", "B) Kapitalismus", "C) Marxismus", "D) Sozialdarwinismus"),
                'C'),
            Question("Wer war der Begründer des Strukturalismus in der Anthropologie?",
                listOf("A) Franz Boas", "B) Claude Lévi-Strauss", "C) Edward B. Tylor", "D) Marvin Harris"),
                'B'),
            Question("Wer schrieb das bekannte Werk „Das Kapital“?",
            listOf("A) Adam Smith", "B) Friedrich Nietzsche", "C) Karl Marx", "D) Max Weber"),
                'C'),
            Question("Welcher Mathematiker entwickelte die Theorie der Analysis?",
                listOf("A) Isaac Newton", "B) Carl Friedrich Gauss", "C) Blaise Pascal", "D) Augustin-Louis Cauchy"),
                'D'),
            Question("Welches Land ist der Ursprungsort des Kabuki-Theaters?",
                listOf("A) Japan", "B) China", "C) Südkorea", "D) Thailand"),
                'A'),
            Question("Welches ist das bekannteste Werk von Miguel de Cervantes?",
                listOf("A) Don Quixote", "B) La Celestina", "C) Lazarillo de Tormes", "D) Guzmán de Alfarache"),
                'A'),
            Question("Wer war der Begründer des Taoismus?",
                listOf("A) Confucius", "B) Lao-Tse", "C) Sun Tzu", "D) Mencius"),
                'B'),
            Question("Welches ist das bekannteste Werk von William Shakespeare?",
                listOf("A) Macbeth", "B) Hamlet", "C) Romeo und Julia", "D) Othello"),
                'B'),
            Question("Welches ist die bekannteste Oper von Richard Wagner?",
                listOf("A) Tristan und Isolde", "B) Die Meistersinger von Nürnberg", "C) Das Rheingold", "D) Die Walküre"),
                'A'),
            Question("Welches ist die älteste bekannte Hochkultur?",
                listOf("A) Maya", "B) Ägypten", "C) Mesopotamien", "D) Indus-Kultur"),
                'B'),
            Question("Wer war der Entdecker des Heliums?",
                listOf("A) Isaac Newton", "B) James Clerk Maxwell", "C) Joseph Priestley", "D) Pierre Janssen"),
                'D'),
            Question("Welcher Philosoph gilt als Begründer der Epistemologie?",
                listOf("A) Plato", "B) René Descartes", "C) Aristotle", "D) Immanuel Kant"),
                'B'),
            Question("Welcher französische Schriftsteller schrieb „Die Blechtrommel“?",
                listOf("A) Albert Camus", "B) Jean-Paul Sartre", "C) Gustave Flaubert", "D) Günter Grass"),
                'D'),
            Question("Welcher österreichische Komponist schrieb die Oper „Don Giovanni“?",
                listOf("A) Wolfgang Amadeus Mozart", "B) Ludwig van Beethoven", "C) Franz Joseph Haydn", "D) Christoph Willibald Gluck"),
                'A'),
            Question("Welcher US-amerikanischer Schriftsteller schrieb „The Great Gatsby“?",
                listOf("A) Ernest Hemingway", "B) F. Scott Fitzgerald", "C) William Faulkner", "D) John Steinbeck"),
                'B'),
            Question("Welcher italienische Philosoph gilt als Begründer der Neuplatonismus?",
                listOf("A) Giordano Bruno", "B) Marsilio Ficino", "C) Pico della Mirandola", "D) Niccolò Machiavelli"),
                'B'),
            Question("Welcher österreichische Psychiater entwickelte die Theorie der Psychoanalyse?",
                listOf("A) Carl Jung", "B) Sigmund Freud", "C) Alfred Adler", "D) Erik Erikson"),
                'B'),
            Question("Welcher US-amerikanischer Schriftsteller schrieb „Moby-Dick“?",
                listOf("A) Nathaniel Hawthorne", "B) Edgar Allan Poe", "C) Mark Twain", "D) Herman Melville"),
                'D'),
            Question("Welcher italienischer Mathematiker entwickelte die Theorie der Algebra?",
                listOf("A) Leonardo da Vinci", "B) Giovanni Fibonacci", "C) Luca Pacioli", "D) Girolamo Cardano"),
                'B'),
            Question("Welcher griechische Philosoph ist der Begründer der Ethik?",
                listOf("A) Socrates", "B) Plato", "C) Aristotle", "D) Zenon von Elea"),
                'C'),
            Question("Welche Art von Teilchen ist ein Photon?",
                listOf("A) Teilchen", "B) Welle", "C) Beides", "D) Keins von beiden"),
                'B'),
            Question("Welcher Planet im Sonnensystem hat den größten Durchmesser?",
                listOf("A) Erde", "B) Mars", "C) Jupiter", "D) Saturn"),
                'C'),
            Question("Welches Land war der erste, der die Kernenergie nutzte?",
                listOf("A) USA", "B) Russland", "C) Großbritannien", "D) Frankreich"),
                'A'),
            Question("Wer war der Entdecker des Pflanzenzellulose-Struktur?",
                listOf("A) Louis Pasteur", "B) Robert Hooke", "C) Anton van Leeuwenhoek", "D) Charles Darwin"),
                'B'),
            Question("Wer entdeckte das Elektron?",
                listOf("A) J.J. Thomson", "B) James Clerk Maxwell", "C) Nikola Tesla", "D) Albert Einstein"),
                'A')
        )
    }
}
