class MediumQuestions {
    companion object {
        val questionsMedium = listOf(
            Question("Wie viele Planeten hat unser Sonnensystem?",
                listOf("A) 8", "B) 9", "C) 10", "D) 11"),
                'A'),
            Question("Was ist das Antonym von dem Wort 'heiß'?",
                listOf("A) Kalt", "B) Warm", "C) Dunkel", "D) Hell"),
                'A'),
            Question("Welches Land ist die Heimat von Nissan?",
                listOf("A) USA", "B) China", "C) Deutschland", "D) Japan"),
                'D'),
            Question("Wie viele Muskeln hat ein Mensch im Körper?",
                listOf("A) 200", "B) 400", "C) 600", "D) 800"),
                'C'),
            Question("Welche Farbe hat das Logo von Amazon?",
                listOf("A) Rot", "B) Grün", "C) Gelb", "D) Blau"),
                'A'),
            Question("Welches Land ist die Heimat von Samsung?",
                listOf("A) USA", "B) China", "C) Deutschland", "D) Südkorea"),
                'D'),
            Question("Welches Jahr endete der Zweite Weltkrieg?",
                listOf("A) 1940", "B) 1941", "C) 1945", "D) 1950"),
                'C'),
            Question("Welche Art von Waffe ist eine Kanone?",
                listOf("A) Handfeuerwaffe", "B) Scharfschützengewehr", "C) Granatwerfer", "D) Artilleriegeschütz"),
                'D'),
            Question("Welches Element ist das häufigste im Universum?",
                listOf("A) Wasserstoff", "B) Helium", "C) Sauerstoff", "D) Stickstoff"),
                'A'),
            Question("Wie viele Kontinente gibt es auf der Erde?",
                listOf("A) 4", "B) 5", "C) 6", "D) 7"),
                'B'),
            Question("Welches Land ist bekannt für seine Pyramiden?",
                listOf("A) Ägypten", "B) China", "C) Griechenland", "D) Indien"),
                'A'),
            Question("Welches Land ist bekannt für seine Mauer, die einst die Teilung symbolisierte?",
                listOf("A) Deutschland", "B) Frankreich", "C) Großbritannien", "D) USA"),
                'A'),
            Question("Welches Land ist bekannt für seine Akropolis?",
                listOf("A) Ägypten", "B) China", "C) Griechenland", "D) Indien"),
                'C'),
            Question("Welche Farbe hat das Logo von Coca Cola?",
                listOf("A) Rot", "B) Grün", "C) Gelb", "D) Blau"),
                'A'),
            Question("Welche Stadt ist die Hauptstadt von Frankreich?",
                listOf("A) Berlin", "B) London", "C) Paris", "D) Rom"),
                'C'),
            Question("Wer war der erste Mensch, der den Mount Everest erklommen hat?",
                listOf("A) Reinhold Messner", "B) Sir Edmund Hillary", "C) Tensing Norgay", "D) George Mallory"),
                'B'),
            Question("Welche Art von Zelle ist bei Tieren und Menschen die häufigste?",
                listOf("A) Muskelzelle", "B) Nervenzelle", "C) Blutzelle", "D) Knochenzelle"),
                'C'),
            Question("Wie heißt das kleinste und älteste Fossil eines Pflanzenfressenden Dinosauriers?",
                listOf("A) Microraptor", "B) Eoraptor", "C) Compsognathus", "D) Velociraptor"),
                'B'),
            Question("Welches Land ist die Heimat des Kameleons?",
                listOf("A) Südafrika", "B) Australien", "C) Madagaskar", "D) Arabische Halbinsel"),
                'C'),
            Question("Wer schrieb das berühmte Drama Othello?",
                listOf("A) William Shakespeare", "B) Edgar Allan Poe", "C) Charles Dickens", "D) Jane Austen"),
                'A'),
            Question("Wie heißt das erste Modell eines elektrischen Automobils, das von Tesla Motors produziert wurde?",
                listOf("A) Model X", "B) Model 3", "C) Model S", "D) Roadster"),
                'D'),
            Question("Welche Art von Technologie wird verwendet, um den Standort eines Geräts zu bestimmen?",
                listOf("A) GPS", "B) NFC", "C) Bluetooth", "D) Wi-Fi"),
                'A'),
            Question("Wer entwickelte das erste elektrische Automobil?",
                listOf("A) Henry Ford", "B) Karl Benz", "C) Gottlieb Daimler", "D) Nicolaus Otto"),
                'B'),
            Question("Wie heißt die Hauptstadt von Frankreich?",
                listOf("A) Paris", "B) Marseille", "C) Lyon", "D) Toulouse"),
                'A'),
            Question("Welches Land ist die Heimat des KFC?",
                listOf("A) USA", "B) Kanada", "C) England", "D) Australien"),
                'A')
        )
    }
}
